version: '3.8'
services:
  db:
    container_name: dashboard_api
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=dashboard-api
      - MYSQL_ROOT_PASSWORD=rFJjmcuf5dhauRMQj
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - db:/var/lib/mysql
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: dashboard-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rFJjmcuf5dhauRMQj
      DB_NAME: dashboard-api
      JWT_SECRET_KEY: ABC
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local