version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=dashboard-api
      - MYSQL_ROOT_PASSWORD=rFJjmcuf5dhauRMQj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: api
    build:
      context: api/
      target: development
    image: dashboard-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rFJjmcuf5dhauRMQj
      DB_NAME: dashboard-api
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local