version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: dashboard_api
    restart: always
    environment:
      - MYSQL_DATABASE=dashboard-api
      - MYSQL_ROOT_PASSWORD=rFJjmcuf5dhauRMQj
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
